#!/usr/bin/env node
// `task reopen` CRASHED ON EVERY SUCCESSFUL RUN, AFTER THE WRITE HAD ALREADY LANDED.
//
// The bug: `const stage` was declared inside the try block and read in the `if (res.ok)` branch
// below it. Block-scoped const does not escape braces, so the success path ended in
// "ReferenceError: stage is not defined" - with the card already reopened.
//
// Why it survived: the ONLY thing broken was the sentence that reports success. The durable write
// went through, the card really moved, and the command reported a crash. A reader sees a stack
// trace and concludes nothing happened. Nothing failed loudly enough to be noticed, and the card
// still changed, so no dashboard alarm rang either.
//
// Both properties are pinned here, because either one alone would pass on the broken build:
//   - the command exits 0 and PRINTS the stage it wrote      (catches the ReferenceError)
//   - the card really is reopened, with done_at cleared      (catches a "fix" that stops writing)
//
// A test that only checked the card state would have passed on the original defect, since the
// write did happen. A test that only checked stdout would pass on a fix that crashed before
// writing. The defect needs both.
//
// Run: node test/task-reopen-stage-ref.test.mjs

import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "reopen-stage-"));
const amqRoot = path.join(tmp, ".agent-mail");
fs.mkdirSync(path.join(amqRoot, "bus"), { recursive: true });
fs.mkdirSync(path.join(amqRoot, "agents"), { recursive: true });

const bin = path.resolve("bin/herdr-amq.mjs");
// AMQ_ME, not AM_ME: the CLI's actor guard reads AMQ_ME and refuses to default, which is correct
// and cost me one probe before I read it.
const env = { ...process.env, AM_ROOT: amqRoot, AMQ_ME: "agsuite-dev" };

function run(args) {
  try {
    return { code: 0, out: execFileSync("node", [bin, ...args], { env, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }) };
  } catch (e) {
    return { code: e.status ?? 1, out: `${e.stdout || ""}${e.stderr || ""}` };
  }
}

// The card id is generated by the CLI, so it is read back from the receipt rather than invented.
// A guessed id would make every assertion below pass vacuously - which is the shape of the bug
// being tested, so the fixture must not repeat it.
function createCard(title) {
  const r = run(["task", "create", "--title", title, "--owner", "agsuite-dev", "--desc", "x"]);
  const m = r.out.match(/(task_\d+_[0-9a-f]+)/);
  assert.ok(m, `could not read a card id out of the create receipt:\n${r.out}`);
  return m[1];
}

let ID = null;

test("reopen prints the stage it wrote and does not throw", () => {
  ID = createCard("probe reopen");
  run(["task", "claim", ID, "--me", "agsuite-dev"]);
  run(["task", "done", ID, "--me", "agsuite-dev", "--proof", "p"]);
  const doneFile = path.join(amqRoot, "bus", "done", `${ID}.md`);
  assert.ok(fs.existsSync(doneFile), `precondition: the card is done. bus: ${fs.readdirSync(path.join(amqRoot, "bus")).join(", ")}`);

  const r = run(["task", "reopen", ID, "--me", "agsuite-dev", "--reason", "probe"]);

  assert.equal(r.code, 0, `reopen must exit 0, not crash. Got ${r.code}:\n${r.out}`);
  assert.doesNotMatch(r.out, /ReferenceError/, `reopen must not throw. Output:\n${r.out}`);
  assert.match(r.out, /REOPENED into in_progress/, `it must NAME the stage it wrote, because the crash was in that sentence. Output:\n${r.out}`);
});

test("the card really was reopened: done_at cleared, status back to in_progress", () => {
  // The half that would still pass on the broken build, and must not regress if someone "fixes"
  // the message by returning before the write.
  assert.ok(ID, "the first test must have created the card this one reads");
  // The board DIRECTORY is `doing`; `in_progress` is the value inside the file. Asserting on the
  // directory name I assumed is the same class of error as the bug: a check that fails for a
  // reason that has nothing to do with the thing under test.
  const file = path.join(amqRoot, "bus", "doing", `${ID}.md`);
  assert.ok(fs.existsSync(file), `the card must be back in in_progress, not still in done. bus has: ${fs.readdirSync(path.join(amqRoot, "bus")).join(", ")}`);
  const text = fs.readFileSync(file, "utf8");
  assert.match(text, /^status: "in_progress"$/m, "status must be in_progress");
  assert.match(text, /^done_at: null$/m, "done_at must be cleared");
});

test("--stage queued is honoured and reported, and an unknown stage is refused", () => {
  const q = run(["task", "reopen", ID, "--me", "agsuite-dev", "--stage", "queued", "--reason", "probe"]);
  assert.equal(q.code, 0, `--stage queued must succeed. Got ${q.code}:\n${q.out}`);
  assert.match(q.out, /REOPENED into queued/, `it must report the stage it was ASKED for. Output:\n${q.out}`);
  assert.ok(
    fs.existsSync(path.join(amqRoot, "bus", "queued", `${ID}.md`)),
    `the card must actually be in queued. bus: ${fs.readdirSync(path.join(amqRoot, "bus")).join(", ")}`,
  );

  const bad = run(["task", "reopen", ID, "--me", "agsuite-dev", "--stage", "nonsense", "--reason", "probe"]);
  assert.equal(bad.code, 1, "an unknown stage must be refused, not silently accepted");
  assert.match(bad.out, /Unknown --stage/, "and it must say which stage it did not understand");
});

test.after(() => fs.rmSync(tmp, { recursive: true, force: true }));
